name: publish

on:
  push:
    branches:
    - main
    - release/*    
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
      with:
        ref: main
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'publish'
        force-add: 'true'
        files: README.md SETUP.MD server.py tests/ utils/ db/ db/backend.db
        name: commiter name
        email: my.github@email.com 
